---
language: node_js
node_js:
  - "4"

sudo: false

cache:
  directories:
    - node_modules
    - $HOME/.yarn-cache

before_install:
  - npm config set spin false
  - npm install -g bower yarn
  - bower --version
  - yarn --version
  - npm install phantomjs-prebuilt
  - node_modules/phantomjs-prebuilt/bin/phantomjs --version

install:
  - yarn install
  - bower install

script:
  - ember test --skip-cleanup
